# Generated by Django 3.2.6 on 2021-09-20 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1', models.PositiveSmallIntegerField(verbose_name='x1')),
                ('y1', models.PositiveSmallIntegerField(verbose_name='y1')),
                ('x2', models.PositiveSmallIntegerField(verbose_name='x2')),
                ('y2', models.PositiveSmallIntegerField(verbose_name='y2')),
                ('color', models.CharField(max_length=7, verbose_name='color')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.page', verbose_name='página')),
            ],
            options={
                'verbose_name': 'Línea',
                'verbose_name_plural': 'Líneas',
                'ordering': ['page__id', 'y1', 'y2', 'x1', 'x2'],
            },
        ),
    ]
