# Generated by Django 3.2.5 on 2021-07-20 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagefolder',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homework.pagefolder', verbose_name='carpeta padre'),
        ),
    ]
