# Generated by Django 3.2.5 on 2021-07-21 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homework.pagefolder', verbose_name='carpeta'),
        ),
        migrations.AlterField(
            model_name='pagefolder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homework.pagefolder', verbose_name='carpeta padre'),
        ),
    ]
