# Generated by Django 3.2.5 on 2021-07-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0009_alter_pagefolder_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='font_size',
            field=models.CharField(max_length=7, verbose_name='tamaño de fuente'),
        ),
    ]
