# Generated by Django 3.2.5 on 2021-07-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0009_alter_pagefolder_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='selected_font',
            field=models.CharField(default='kid', max_length=10, verbose_name='Fuente'),
        ),
    ]
