# Generated by Django 3.2.5 on 2021-07-22 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0010_alter_label_font_size'),
        ('homework', '0010_profile_selected_font'),
    ]

    operations = [
    ]
