# Generated by Django 3.2.5 on 2021-07-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0011_merge_20210722_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='.', max_length=256, verbose_name='nombre completo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='selected_font',
            field=models.CharField(default='infantil', max_length=10, verbose_name='Fuente'),
        ),
    ]
